
base:
  DEBUG: true
  ALLOWED_HOSTS:
    - "*"
  SECRET_KEY: "django-insecure-kjhq6onltf0t1&)+wi_52$0g9$)vj@$^%4psmcu#8p2ups*p@x"
  OPEN_METEO_API_URL: "https://api.open-meteo.com/v1/forecast"

database:
  HOST: "localhost"
  NAME: "travel_recommend"
  USER: "database_user"
  PASSWORD: "password"
  PORT: "5432"

